import Head from 'next/head';

const Header = () => (
  <Head>
    <title>Next Planets</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export { Header };
